import './globals.scss'
import { Inter } from 'next/font/google'
import { Header } from './Header'
import { Footer } from './Footer'
import { CounterProvider } from '@/context/CounterProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: '#ffffff',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head />
      <body className={inter.className}>
        <Header />
        <CounterProvider>{children}</CounterProvider>
        <Footer />
      </body>
    </html>
  )
}
