import './globals.scss'
import { Inter } from 'next/font/google'
import { Header } from './Header'
import { Footer } from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: '#ffffff',
}

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode
  team: React.ReactNode
  analytics: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head />
      <body className={inter.className}>
        <Header />
        <div>{children}</div>
        <div>{team}</div>
        <div>{analytics}</div>
        <Footer />
      </body>
    </html>
  )
}
